services:
    #MongoDB service
    mongo_db:
        container_name: mongodb_container
        image: mongo:8.0.4
        ports:
            - 27017:27017 # enable outside docker only for development
        restart: unless-stopped
        volumes: 
            - mongo_db:/data/db

    #NotePass
    notepass:
        secrets:
            - secret_key
            - iv
        build: .
        restart: unless-stopped
        ports:
            - 4000:3000
        
        environment:
            PORT: 3000
            LOCAL_DATA_CONNECTION_STRING: mongodb://mongo_db:27017/notepass
            SECRET_KEY: /run/secrets/secret_key
            IV: /run/secrets/iv
            NODE_ENV: development
        depends_on:
            - mongo_db        

volumes:
    mongo_db:
        driver: local

secrets:
    secret_key:
        file: ./secret_key.txt  #16 long hex
        # external: true
    iv:
        file: ./iv.txt          #32 long hex
        # external: true
